# Generated by Django 5.1.1 on 2024-09-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_student_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
