# Generated by Django 5.1.1 on 2024-09-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Mobile_Number', models.CharField(max_length=200, null=True)),
                ('Course', models.CharField(max_length=200, null=True)),
                ('fees', models.IntegerField(default=0)),
            ],
        ),
    ]
